/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/shiny/871.glb -o models/gltfjsx/shiny/871.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function 871(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/871.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <group position={[0, 0, 86.852]}>
          <mesh geometry={nodes.Object_1.geometry} material={materials.color_15490603} />
          <mesh geometry={nodes.Object_1_1.geometry} material={materials.color_5588052} />
          <mesh geometry={nodes.Object_1_2.geometry} material={materials.color_16768282} />
          <mesh geometry={nodes.Object_1_3.geometry} material={materials.color_3225146} />
          <mesh geometry={nodes.Object_1_4.geometry} material={materials.color_7565690} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/871.glb')
