/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/134.glb -o models/gltfjsx/regular/134.jsx 
Author: seth the yutyrannus (https://sketchfab.com/slang107123456789)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokedex-3d-pro-vaporeon-a0eea1c4b9584af5b49fa26855d39343
Title: Pokedex 3d Pro Vaporeon
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 134(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/134.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="58f7867bc8784d51811d6035e59697d5fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={100}>
                  <group name="Object_5_1">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_75" scale={100} />
                    <group name="Object_77" scale={100} />
                    <group name="Object_79" scale={100} />
                    <group name="Object_81" scale={100} />
                    <group name="Object_83" scale={100} />
                    <group name="Object_85" scale={100} />
                    <group name="Object_87" scale={100} />
                    <skinnedMesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.Mouth} skeleton={nodes.Object_76.skeleton} />
                    <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material} skeleton={nodes.Object_78.skeleton} />
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.BodyC} skeleton={nodes.Object_80.skeleton} />
                    <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.BodyB} skeleton={nodes.Object_82.skeleton} />
                    <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.Body} skeleton={nodes.Object_84.skeleton} />
                    <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.Body} skeleton={nodes.Object_86.skeleton} />
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Body} skeleton={nodes.Object_88.skeleton} />
                  </group>
                </group>
                <group name="Object_0" scale={100} />
                <group name="Object_1" scale={100} />
                <group name="Object_2_1" scale={100} />
                <group name="Object_3" scale={100} />
                <group name="Object_4" scale={100} />
                <group name="Object_5" scale={100} />
                <group name="Object_6" scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/134.glb')
