/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/196.glb -o models/gltfjsx/regular/196.jsx 
Author: seth the yutyrannus (https://sketchfab.com/slang107123456789)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokedex-3d-pro-espeon-6e839167f75c47129d03dc0802d838d6
Title: Pokedex 3d Pro Espeon
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 196(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/196.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="79fd15c2313b4eaf92594c854d210059fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" position={[3.667, 0, 0]} scale={100}>
                  <group name="Object_5_1">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_79" position={[3.667, 0, 0]} scale={100} />
                    <group name="Object_81" position={[3.667, 0, 0]} scale={100} />
                    <group name="Object_83" position={[3.667, 0, 0]} scale={100} />
                    <group name="Object_85" position={[3.667, 0, 0]} scale={100} />
                    <group name="Object_87" position={[3.667, 0, 0]} scale={100} />
                    <group name="Object_89" position={[3.667, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Mouth} skeleton={nodes.Object_80.skeleton} />
                    <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material} skeleton={nodes.Object_82.skeleton} />
                    <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.BodyB} skeleton={nodes.Object_84.skeleton} />
                    <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.BodyA} skeleton={nodes.Object_86.skeleton} />
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.BodyA} skeleton={nodes.Object_88.skeleton} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.BodyA} skeleton={nodes.Object_90.skeleton} />
                  </group>
                </group>
                <group name="Object_0" position={[3.667, 0, 0]} scale={100} />
                <group name="Object_1" position={[3.667, 0, 0]} scale={100} />
                <group name="Object_2_1" position={[3.667, 0, 0]} scale={100} />
                <group name="Object_3" position={[3.667, 0, 0]} scale={100} />
                <group name="Object_4" position={[3.667, 0, 0]} scale={100} />
                <group name="Object_5" position={[3.667, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/196.glb')
