/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/197.glb -o models/gltfjsx/regular/197.jsx 
Author: seth the yutyrannus (https://sketchfab.com/slang107123456789)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokedex-3d-pro-umbreon-8fda51cf8e664142ae6f037b68993fcb
Title: Pokedex 3d Pro Umbreon
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 197(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/197.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="7578c9bd27664adeaa2015930e8a70d2fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={100}>
                  <group name="Object_5_1">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_67" scale={100} />
                    <group name="Object_69" scale={100} />
                    <group name="Object_71" scale={100} />
                    <group name="Object_73" scale={100} />
                    <group name="Object_75" scale={100} />
                    <group name="Object_77" scale={100} />
                    <group name="Object_79" scale={100} />
                    <group name="Object_81" scale={100} />
                    <skinnedMesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material} skeleton={nodes.Object_68.skeleton} />
                    <skinnedMesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Mouth} skeleton={nodes.Object_70.skeleton} />
                    <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.Body} skeleton={nodes.Object_72.skeleton} />
                    <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Body} skeleton={nodes.Object_74.skeleton} />
                    <skinnedMesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.EyeE} skeleton={nodes.Object_76.skeleton} />
                    <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.MouthE} skeleton={nodes.Object_78.skeleton} />
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.BodyE} skeleton={nodes.Object_80.skeleton} />
                    <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.BodyE} skeleton={nodes.Object_82.skeleton} />
                  </group>
                </group>
                <group name="Object_0" scale={100} />
                <group name="Object_1" scale={100} />
                <group name="Object_2_1" scale={100} />
                <group name="Object_3" scale={100} />
                <group name="Object_4" scale={100} />
                <group name="Object_5" scale={100} />
                <group name="Object_6" scale={100} />
                <group name="Object_7" scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/197.glb')
