/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/470.glb -o models/gltfjsx/regular/470.jsx 
Author: seth the yutyrannus (https://sketchfab.com/slang107123456789)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokedex-3d-pro-leafeon-49bb156c9e33401a9a73b63e48bd935f
Title: Pokedex 3d Pro Leafeon
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 470(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/470.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.167}>
          <group name="6d813718f7374042a2bdf0a17b5058acfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={100}>
                  <group name="Object_5_1">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_102" scale={100} />
                    <group name="Object_104" scale={100} />
                    <group name="Object_106" scale={100} />
                    <group name="Object_108" scale={100} />
                    <group name="Object_110" scale={100} />
                    <group name="Object_112" scale={100} />
                    <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.material} skeleton={nodes.Object_103.skeleton} />
                    <skinnedMesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.Mouth} skeleton={nodes.Object_105.skeleton} />
                    <skinnedMesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.Body} skeleton={nodes.Object_107.skeleton} />
                    <skinnedMesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.Body} skeleton={nodes.Object_109.skeleton} />
                    <skinnedMesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.Body} skeleton={nodes.Object_111.skeleton} />
                    <skinnedMesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.Body} skeleton={nodes.Object_113.skeleton} />
                  </group>
                </group>
                <group name="Object_0" scale={100} />
                <group name="Object_1" scale={100} />
                <group name="Object_2_1" scale={100} />
                <group name="Object_3" scale={100} />
                <group name="Object_4" scale={100} />
                <group name="Object_5" scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/470.glb')
