/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/943.glb -o models/gltfjsx/regular/943.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function 943(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/943.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[-8.662, -0.01, 0.007]}>
        <group position={[8.662, 0.01, -0.007]}>
          <primitive object={nodes.GLTF_created_14_rootJoint} />
          <skinnedMesh geometry={nodes.Object_1029.geometry} material={materials.pm1113_00_51_body_a_alb} skeleton={nodes.Object_1029.skeleton} />
          <skinnedMesh geometry={nodes.Object_1030.geometry} material={materials.pm1113_00_51_body_b_alb} skeleton={nodes.Object_1030.skeleton} />
          <skinnedMesh geometry={nodes.Object_1031.geometry} material={materials.pm1113_00_51_eye_alb} skeleton={nodes.Object_1031.skeleton} />
          <skinnedMesh geometry={nodes.Object_1033.geometry} material={materials.pm1113_00_51_body_b_alb} skeleton={nodes.Object_1033.skeleton} />
        </group>
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials['eyeball_r.002']} position={[-8.662, -0.01, 0.007]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.pm1077_00_00_body_b_alb} position={[-8.662, -0.01, 0.007]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.pm1077_00_00_body_a_alb} position={[-8.662, -0.01, 0.007]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['eyeball_l.002']} position={[-8.662, -0.01, 0.007]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/943.glb')
