/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 58.glb -o ../../gltfjsx/hisuian/58.jsx 
Author: Cubone0711 (https://sketchfab.com/Cubone0711)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-pokemon-home-058-hisuian-growlithe-976b3601a5494970b13d820a243f625a
Title: Mobile - Pokemon HOME - 058 Hisuian Growlithe
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/hisuian/58.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="hisuian_growlithe_with_animationfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={50}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_78" scale={50} />
                    <group name="Object_80" scale={50} />
                    <group name="Object_82" scale={50} />
                    <group name="Object_84" scale={50} />
                    <group name="Object_86" scale={50} />
                    <group name="Object_88" scale={50} />
                    <group name="Object_90" scale={50} />
                    <group name="Object_92" scale={50} />
                    <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials['pm0058_00_41-Body00']} skeleton={nodes.Object_79.skeleton} />
                    <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials['pm0058_00_41-Body00']} skeleton={nodes.Object_81.skeleton} />
                    <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials['pm0058_00_41-Body01']} skeleton={nodes.Object_83.skeleton} />
                    <skinnedMesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials['pm0058_00_41-Body00']} skeleton={nodes.Object_85.skeleton} />
                    <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials['pm0058_00_41-Body00']} skeleton={nodes.Object_87.skeleton} />
                    <skinnedMesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials['pm0058_00_41-Body00']} skeleton={nodes.Object_89.skeleton} />
                    <skinnedMesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials['pm0058_00_41-Body01']} skeleton={nodes.Object_91.skeleton} />
                    <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials['pm0058_00_41-Body00']} skeleton={nodes.Object_93.skeleton} />
                  </group>
                </group>
                <group name="pm0058_00_41_BodySkin" scale={50} />
                <group name="pm0058_00_41_NailSkin" scale={50} />
                <group name="pm0058_00_41_HairASkin" scale={50} />
                <group name="pm0058_00_41_MouthSkin" scale={50} />
                <group name="pm0058_00_41_TongueSkin" scale={50} />
                <group name="pm0058_00_41_EarSkin" scale={50} />
                <group name="pm0058_00_41_HairBSkin" scale={50} />
                <group name="pm0058_00_41_TeethSkin" scale={50} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/hisuian/58.glb')
