/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 52.glb -o ../../gltfjsx/galar/52.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/galar/52.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0052_00_31_body_mesh_shape_body_a.geometry} material={materials['body_a.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_body_mesh_shape_body_b_00.geometry} material={materials['body_b_00.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_body_mesh_shape_body_b_01.geometry} material={materials['body_b_01.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_claw_l_mesh_shape_body_b_00.geometry} material={materials['body_b_00.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_claw_r_mesh_shape_body_b_00.geometry} material={materials['body_b_00.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_eye_mesh_shape_l_eye.geometry} material={materials['l_eye.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_eye_mesh_shape_r_eye.geometry} material={materials['r_eye.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_tooth_a_mesh_shape_body_b_00.geometry} material={materials['body_b_00.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0052_00_31_tooth_b_mesh_shape_body_b_00.geometry} material={materials['body_b_00.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/galar/52.glb')
