/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3.glb -o ../../gltfjsx/gmax/3.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/gmax/3.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.pm0003_81_00} />
        <skinnedMesh geometry={nodes.pm0003_81_00_BodyCSkin.geometry} material={materials.BodyC00} skeleton={nodes.pm0003_81_00_BodyCSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0003_81_00_BodyDSkin.geometry} material={materials.BodyA01} skeleton={nodes.pm0003_81_00_BodyDSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0003_81_00_BodyASkin_2.geometry} material={materials.Eye} skeleton={nodes.pm0003_81_00_BodyASkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0003_81_00_BodyASkin_3.geometry} material={materials.BodyA00} skeleton={nodes.pm0003_81_00_BodyASkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0003_81_00_BodyBSkin_2.geometry} material={materials.BodyB02} skeleton={nodes.pm0003_81_00_BodyBSkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0003_81_00_BodyBSkin_3.geometry} material={materials.BodyB00} skeleton={nodes.pm0003_81_00_BodyBSkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0003_81_00_BodyBSkin_4.geometry} material={materials.BodyB01} skeleton={nodes.pm0003_81_00_BodyBSkin_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/opt/gmax/3.glb')
